/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 01 19:14:23 GMT 2019
 */

import com.krizsanandras.projectwob.DatabaseHelper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.fail;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DatabaseHelper_ESTest extends DatabaseHelper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
        try {
          DatabaseHelper databaseHelper0 = null;
          try {
            databaseHelper0 = new DatabaseHelper();
            fail("Expecting exception: PSQLException");
          
          } catch(Throwable e) {
             //
             // Something unusual has occurred to cause the driver to fail. Please report this exception.
             //
             verifyException("org.postgresql.Driver", e);
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }
}
